In [1]:
%matplotlib inline
import numpy 
from matplotlib import pyplot
from matplotlib import rcParams
rcParams['font.family'] = 'serif'
rcParams['font.size'] = 16

In [2]:
nx = 81
dx = .25
dt = .0002   
gamma = 1.4
t = 0.01 #Since all caculations at time = 0.01s
nt = int(t/dt)+1

In [3]:
x = numpy.linspace(-10, 10, nx)
rho = numpy.ones(nx)
rho[40:] = 0.125

u = numpy.zeros(nx)

p = numpy.ones(nx)
p[0:40] = 100000.
p[40:] = 10000.
p

array([ 100000.,  100000.,  100000.,  100000.,  100000.,  100000.,
        100000.,  100000.,  100000.,  100000.,  100000.,  100000.,
        100000.,  100000.,  100000.,  100000.,  100000.,  100000.,
        100000.,  100000.,  100000.,  100000.,  100000.,  100000.,
        100000.,  100000.,  100000.,  100000.,  100000.,  100000.,
        100000.,  100000.,  100000.,  100000.,  100000.,  100000.,
        100000.,  100000.,  100000.,  100000.,   10000.,   10000.,
         10000.,   10000.,   10000.,   10000.,   10000.,   10000.,
         10000.,   10000.,   10000.,   10000.,   10000.,   10000.,
         10000.,   10000.,   10000.,   10000.,   10000.,   10000.,
         10000.,   10000.,   10000.,   10000.,   10000.,   10000.,
         10000.,   10000.,   10000.,   10000.,   10000.,   10000.,
         10000.,   10000.,   10000.,   10000.,   10000.,   10000.,
         10000.,   10000.,   10000.])

In [4]:
rho

array([ 1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,
        1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,
        1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,
        1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,
        1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,
        0.125,  0.125,  0.125,  0.125,  0.125,  0.125,  0.125,  0.125,
        0.125,  0.125,  0.125,  0.125,  0.125,  0.125,  0.125,  0.125,
        0.125,  0.125,  0.125,  0.125,  0.125,  0.125,  0.125,  0.125,
        0.125,  0.125,  0.125,  0.125,  0.125,  0.125,  0.125,  0.125,
        0.125,  0.125,  0.125,  0.125,  0.125,  0.125,  0.125,  0.125,
        0.125])

In [5]:
u

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.])

In [6]:
eT = p/(gamma-1)/rho + 0.5*u**2

In [7]:
u1 = rho
u2 = rho*u
u3 = rho*eT

In [8]:
def computef1(u1, u2, u3):
    return u2
def computef2(u1, u2, u3):
    return u2**2/u1 + (gamma-1)*(u3 - 0.5*u2**2/u1)
def computef3(u1, u2, u3):
    return (u3 + (gamma - 1)*(u3 - 0.5*u2**2/u1))*u2/u1

In [9]:
def mainfunction(u1, u2, u3, dx, dt, nx, nt):
    u1n = numpy.zeros((nt, len(u1)))
    u2n = numpy.zeros((nt, len(u2)))
    u3n = numpy.zeros((nt, len(u3)))
    
    u1star = numpy.zeros(nx)
    u2star = numpy.zeros(nx)
    u3star = numpy.zeros(nx)
    
    u1n[:,:] = u1.copy()
    u2n[:,:] = u2.copy()
    u3n[:,:] = u3.copy()
    
    u1star = u1.copy()
    u2star = u2.copy()
    u3star = u3.copy()
    
    for i in range(1, nt):
        f1 = computef1(u1, u2, u3)
        f2 = computef2(u1, u2, u3)
        f3 = computef3(u1, u2, u3)
        
        u1star[:-1] = 0.5*(u1[:-1] + u1[1:]) - (dt/(2*dx))*(f1[1:] - f1[:-1])
        u2star[:-1] = 0.5*(u2[:-1] + u2[1:]) - (dt/(2*dx))*(f2[1:] - f2[:-1])
        u3star[:-1] = 0.5*(u3[:-1] + u3[1:]) - (dt/(2*dx))*(f3[1:] - f3[:-1])
        
        f1star = computef1(u1star, u2star, u3star)
        f2star = computef2(u1star, u2star, u3star)
        f3star = computef3(u1star, u2star, u3star)
        
        u1n[i,1:] = u1[1:] - (dt/dx)*(f1star[1:] - f1star[:-1])
        u2n[i,1:] = u2[1:] - (dt/dx)*(f2star[1:] - f2star[:-1])
        u3n[i,1:] = u3[1:] - (dt/dx)*(f3star[1:] - f3star[:-1])
        
        u1 = u1n[i].copy()
        u2 = u2n[i].copy()
        u3 = u3n[i].copy()
        
       
    return u1n, u2n, u3n

In [10]:
un = mainfunction(u1, u2, u3, dx, dt, nx, nt)

In [11]:
u1nx = un[0] # first output's array is u1n
u1x = u1nx[int(t/dt),int((10+2.5)/dx)] # find the value at time 0.01s and x=2.5m

u2nx = un[1] # second output's array is u2n
u2x = u2nx[int(t/dt),int((10+2.5)/dx)] # find the value at time 0.01s and x=2.5m

u3nx = un[2] # third output's array is u3n
u3x = u3nx[int(t/dt),int((10+2.5)/dx)] # find the value at time 0.01s and x=2.5m

In [12]:
density = u1x
velocity = u2x/u1x
eTx = u3x/u1x
pressure = (density*eTx - density*0.5*velocity**2)*(gamma-1)

In [13]:
print('At x=2.5m, the density is {:.2f} kg/m^3'.format(density))

At x=2.5m, the density is 0.37 kg/m^3


In [14]:
print('At x=2.5m, the velocity is {:.2f} m/s'.format(velocity))

At x=2.5m, the velocity is 292.61 m/s


In [15]:
print('At x=2.5m, the pressure is {:.2f} N/m^2'.format(pressure))

At x=2.5m, the pressure is 30250.89 N/m^2
